# Generated by Django 2.1 on 2019-06-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField(blank=True, max_length=1024, null=True, verbose_name='文字')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='图片')),
                ('gauge_type', models.IntegerField(choices=[(0, 'text'), (1, 'picture')], default=0, verbose_name='发布类型')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('open_type', models.IntegerField(choices=[('0', '公开'), ('1', '喜欢我的'), ('2', '我喜欢的'), ('3', '相互喜欢')], default=0, verbose_name='公开类型')),
                ('like_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数')),
                ('transmit', models.BooleanField(default=False, verbose_name='是否转发')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='地址')),
                ('labels', models.CharField(max_length=1024, null=True, verbose_name='标签')),
            ],
            options={
                'db_table': 'dynamic_talk',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='是否点赞')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
            ],
            options={
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='Report_Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(blank=True, max_length=255, null=True, verbose_name='举报原因')),
                ('result', models.CharField(blank=True, max_length=255, null=True, verbose_name='反馈结果')),
                ('report_state', models.IntegerField(choices=[(0, '审核中'), (1, '反馈结果')], default=0, verbose_name='审核状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('is_del', models.BooleanField(default=False)),
                ('dynamictalk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dynamictalk.DynamicTalk', verbose_name='用户动态')),
            ],
            options={
                'db_table': 'report_friends',
            },
        ),
    ]
