# Generated by Django 2.1 on 2019-06-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='upload/addphoto', verbose_name='照片')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='upload/addphoto', verbose_name='照片')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='upload/addphoto', verbose_name='照片')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='upload/addphoto', verbose_name='照片')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='upload/addphoto', verbose_name='照片')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='upload/addphoto', verbose_name='照片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'addphoto',
            },
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'count',
            },
        ),
        migrations.CreateModel(
            name='MeetLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.IntegerField(verbose_name='喜欢人的id')),
                ('like_time', models.DateTimeField(auto_now_add=True, verbose_name='喜欢时间')),
                ('user', models.ManyToManyField(to='user.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'meetlike',
            },
        ),
        migrations.CreateModel(
            name='MeetNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(verbose_name='距离')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(max_length=2, verbose_name='性别')),
                ('site', models.CharField(max_length=100, null=True, verbose_name='相遇地点')),
                ('meettime', models.DateTimeField(auto_now=True, verbose_name='相遇时间')),
                ('meetcount', models.IntegerField(verbose_name='遇见编号')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='纬度')),
                ('friend', models.ManyToManyField(to='user.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'meetnum',
            },
        ),
        migrations.CreateModel(
            name='MeetSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.CharField(max_length=11, null=True, verbose_name='喜欢人的id')),
                ('meettime', models.DateTimeField(auto_now_add=True, verbose_name='相遇时间')),
                ('nums', models.IntegerField(null=True, verbose_name='相遇次数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'meetsite',
            },
        ),
        migrations.CreateModel(
            name='MeetUnlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=512, verbose_name='封面图路径')),
                ('friend_id', models.IntegerField(verbose_name='不喜欢人的id')),
                ('user', models.ManyToManyField(to='user.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'meetunlike',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appName', models.CharField(max_length=10, verbose_name='项目名称')),
                ('packageName', models.CharField(max_length=20, verbose_name='包名')),
                ('versionCode', models.CharField(max_length=12, verbose_name='版本码')),
                ('versionNumber', models.IntegerField(verbose_name='版本编号')),
                ('fileUrl', models.CharField(max_length=100, verbose_name='文件地址')),
                ('fileName', models.CharField(max_length=30, verbose_name='文件名字')),
                ('updateTime', models.CharField(max_length=30, verbose_name='更新时间')),
                ('versionContent', models.CharField(max_length=1024, verbose_name='版本内容')),
            ],
            options={
                'db_table': 'version',
            },
        ),
    ]
