# Generated by Django 2.1 on 2019-06-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamictalk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centent', models.TextField(blank=True, null=True, verbose_name='反馈内容')),
                ('centent_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='反馈类型')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Lable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.IntegerField(choices=[(1, '运动'), (2, '游戏'), (3, '摄影'), (4, '金融'), (5, '汽车'), (6, '房产'), (7, '旅游'), (8, '家居'), (9, '穿搭'), (10, '美食'), (11, '生活'), (12, '商务'), (13, '美容'), (14, '科技'), (15, '休闲'), (16, '教育'), (17, '政法'), (18, '养生')], verbose_name='标签')),
            ],
            options={
                'db_table': 'lable',
            },
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_id', models.IntegerField(blank=True, null=True, verbose_name='被关注用户ID')),
                ('is_friends', models.BooleanField(default=False, verbose_name='是否互关')),
            ],
            options={
                'db_table': 'relationships',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名')),
                ('mobile', models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('constellation', models.IntegerField(blank=True, choices=[(1, '白羊座'), (2, '金牛座'), (3, '双子座'), (4, '巨蟹座'), (5, '狮子座'), (6, '处女座'), (7, '天秤座'), (8, '天蝎座'), (9, '射手座'), (10, '摩羯座'), (11, '水瓶座'), (12, '双鱼座')], null=True, verbose_name='星座')),
                ('is_alter', models.BooleanField(default=False, verbose_name='是否修改')),
                ('scope', models.CharField(max_length=124, verbose_name='地区')),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='个性签名')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='照片')),
                ('is_first', models.IntegerField(blank=True, null=True, verbose_name='是否首张')),
                ('default_display', models.IntegerField(blank=True, null=True, verbose_name='默认展示')),
                ('img_type', models.IntegerField(blank=True, choices=[(1, '头像'), (2, '相册'), (3, '说说')], null=True, verbose_name='图片类型')),
                ('dynamictalk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamictalk.DynamicTalk', verbose_name='动态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'user_img',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='免打扰开始时间')),
                ('end_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='免打扰结束时间')),
                ('inform_method', models.CharField(blank=True, max_length=30, null=True, verbose_name='消息通知')),
                ('hint_method', models.CharField(blank=True, max_length=30, null=True, verbose_name='提示方式')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'user_token',
            },
        ),
        migrations.AddField(
            model_name='relationships',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='lable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
    ]
